id: P98A98BD6
initial_creation_type: ocr
source_metadata:
  volumes:
    a1a0a779b5ad437594cc7b0650fd713a:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: ནག་པོ་ཆེན་པོའི་འཕྲིན་ལས་གསང་བའི་སྒྲུབ་ཐབས།
      total_pages: 1856
      volume_number: 14
