id: D98C9EBAB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:48:44+00:00'
last_modified: '2022-05-26T08:13:56.942722+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '4783':
      image_group_id: I1PD95859
      title: ནག་པོ་ཆེན་པོའི་འཕྲིན་ལས་གསང་བའི་སྒྲུབ་ཐབས།
      total_pages: 1856
      order: 14
      base_file: 4783.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
